### ISSUE TITLE
cannot send from wallet cannot find much on this problem some help would be greatly appreciated thanks 

### ISSUE THREAD

**Issue by mbz6720** [hivewallet/hive-js#238] opened 2015-07-12 17:17 UTC
![screenshot 5](https://cloud.githubusercontent.com/assets/13302011/8638954/40b93d1c-2898-11e5-851e-62f1dcdeba00.png)

**Comment by mbz6720** [comment] 2015-07-13 06:41
hello i cannot send from my hive litecoin web wallet or ios wallet from my iphone i first had this problem when i tried to send a transaction for about 99 ltc the ltc were taken out of my hive wallet and i checked the transaction on block explorer and got 0 confirmations after about 4 hours i checked again still no confirmations a short time later i opened my hive wallet on my iphone and noticed the 99 ltc i sent out were back in there and i could find no record of the transaction in my wallet history or anywhere and i did not save the transaction id ever since then i have not been able to send anything from my wallet although it can recieve i sent from another wallet to see if i could recieve which i could the error i am getting is transaction failed please make sure you are connectd to the internet ive also tried the staging site for hive and nothing is working the time of the transaction i sent out that got rejected was approx. 2 pm friday july 10th

**Comment by mbz6720** [comment] 2015-07-13 15:53
my issue is resolved I guess it just resolved it self after 3 days I woke up this morning and tried to send and it allowed me to

**Comment by Dazzr** [comment] 2015-07-13 19:11
Same situation for me. Thing is Friday july 10th my 550 LTC transaction was rejected. The supplier let the request expire because they did not receive coins. Later it popped up in my send screen en vanished again. Today aprox 1130 it however was visible again.. but, got somehow (and by someone) confirmed and now I lost that 550 LTC coins. They are gone.. I contacted my suppliers (Litebit and Shapeshift) and they did not own that adress and did not receive the coins. It started with a weekend of failed transactions. Sorry I post it here, but the support messages seem to only create an automated ticket.. What's wrong? And what now? 550 LTC gone and less confidence in the wallet.. So you can imagine I hope :-(

Same message about "transaction failed please make sure you are connected to the internet" I was / am always :-(

**Comment by w-hive** [comment] 2015-07-16 01:02
Can you guys try putting your passphrases into this:

http://hive-js.herokuapp.com

@weilu is currently working on timeout issues related to this problem.

**Comment by w-hive** [comment] 2015-07-16 01:10
Closing this and other redundant issues now; #237 and #239 exist to consolidate. You guys may continue to comment here however.

**Closed by w-hive** 2015-07-16 01:10 UTC

**Comment by Dazzr** [comment] 2015-07-16 05:05
Hi there. Yes. I put in the passphrase. 
Dylan

Date: Wed, 15 Jul 2015 18:02:26 -0700

**Comment by w-hive** [comment] 2015-07-16 09:49
@Dazzr and... what happened? Did it work?

**Comment by Dazzr** [comment] 2015-07-16 09:53
Yes. It did work. But, that actually never not worked ...

**Comment by Dazzr** [comment] 2015-07-16 09:54
Or.. what should it do?

My problem was the fact that I lost coins due to a failed transaction.. So it seems.

**Comment by w-hive** [comment] 2015-07-16 10:00
@dazzr Are you the guy who emailed us? If so, we're still looking into that. But I maintain: I cannot imagine any way that a failed transaction could have caused you to lose any coins. So either you still have them (not displayed) or the transaction was actually successful. Hive certainly would not send to an arbitrary address, at least in the absence of malware etc.

**Comment by Dazzr** [comment] 2015-07-16 10:06
Yes I am that guy ;-)
The wallet opens.
Well the amount is still on the designated adress. So.. I think it is not displayed in my wallet and I can not access it. There are other ways, but I am a too newbie to do that right now. So.. for me they "feel lost".
Definately no malware. Also, not all the coins were transferred. The coincidence is that I tried to transfer via a failed transaction an exact te same amount. 

Date: Thu, 16 Jul 2015 03:00:49 -0700

**Comment by w-hive** [comment] 2015-07-16 10:20
OK. I just can't imagine any way that the coins could be arbitrarily sent to another address. Literally it seems impossible. But we'll keep looking into it...

**Comment by Dazzr** [comment] 2015-07-16 10:44
I understand. Lets hope that it was some sort of fantastic smart new bug. If they are not displayed.. How can I tackle that one?

Basically a tough one. Because with the facts in mind and the decentralized concept at the end it leaves me with minus 550 coins. 

Thanks :-)

**Comment by Dazzr** [comment] 2015-07-16 21:33
There was this thing about "that I still have them "not displayed"". How can I check that?

**Comment by w-hive** [comment] 2015-07-17 00:34
Well for one thing you can take your passphrase and put it into bip32.org and get your private key out, and then import it into another wallet, and do a thorough analysis of the resulting transaction list after it rebuilds. :)

**Comment by Dazzr** [comment] 2015-07-17 03:49
Sorry ask which one is then the private key?

Verstuurd vanaf mijn iPhone
